spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
server:
  context-path: /manager
  port: 8081